version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - /home/dina/Desktop/Demoes/jenkins/jenkins-data/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      # - /home/dina/.kube:/root/.kube
      - ~/.minikube:/home/dina/.minikube
    networks:
      - minikube
    user: root

networks:
  minikube:
    external: true




